### PR TITLE
Improve logging.

### PR DESCRIPTION
**Pull request by jmirabel**
@olivier-stasse This will be helpful for calibration next week.

### CODE REVIEW

**Comment by nim65s** [comment]
https://gepgitlab.laas.fr/gsaurel/roscontrol_sot/pipelines/8169/builds ; LGTM, apart from the style. @olivier-stasse wants the code in this repo fit in 80 cols.

I can can either merge this and add a reformat commit, or let you amend your commits, as you prefer.

And after that, I'll make a release :)

**Comment by jmirabel** [comment]
I let you merge and format.

off-topic: how can I configure vim with respect to clang-format ?

**Comment by nim65s** [comment]
For vim, https://clang.llvm.org/docs/ClangFormat.html#vim-integration should be the better way, but unfortunately, it doesn't work, as ubuntu provides a vim compiled with python 3 support, and this script /usr/share/clang/clang-format-6.0/clang-format.py is for python 2…

But you can use https://github.com/rhysd/vim-clang-format ; with:
```
let g:clang_format#command = 'clang-format-6.0'
let g:clang_format#auto_format = 1
```

This should read the `.clang-format` file @olivier-stasse put here, and format the code as needed :)

**Comment by jmirabel** [comment]
> But you can use https://github.com/rhysd/vim-clang-format ; with:

Thanks. That works.

**Pull request merged**
